name: ci
run-name: change request by ${{ github.actor }}
on: [pull_request]
jobs: 
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno check src/mod.ts
      - run: deno check src/cargo/mod.ts
      - run: deno check src/cargo/tasks/mod.ts
      - run: deno check src/hooks/mod.ts
      - run: deno check src/platform/browser/mod.ts
      - run: deno check src/platform/server/mod.ts
      - run: deno check src/state/mod.ts
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test --allow-read